---

spring:
	profiles: production


x-microservice.config-test-value: production-profile

---

spring:
	profiles: development


x-microservice.config-test-value: development-profile

---

spring:
	profiles: testing


x-microservice.config-test-value: testing-profile



